# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: php:7.2

# Select what we should cache between builds
cache:
    paths:
        - vendor/

before_script:
    - curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

test:
    script:
        - composer install
        - vendor/bin/phpunit --bootstrap vendor/autoload.php --testdox tests
