# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: gitlab.fancy.org.uk:5005/speechmore/laravel-docker:latest

# Select what we should cache between builds
cache:
    paths:
        - vendor/

test:
    script:
        - composer install
        - vendor/bin/phpunit --bootstrap vendor/autoload.php --testdox tests
