<?php

// Uncomment and fill out relevant fields to add support for a property
// Properties must be in the following format:
// (name, type, description, validation), where
// name (required) is a 4 character string,
// type (required) is a valid property type (str, dec, hex, log, mac, cfb, bin)
// description (required) is a short, one-line description of the property
// validation (optional) is eval()d to verify the input value for setting a property

return [
    ['buil', 'str', 'Build string?', null],
    ['DynS', 'cfb', 'DNS', null],
    // ['cfpf', '', '', null],
    // ['cloC', '', '', null],
    // ['cloD', '', '', null],
    // ['conf', '', '', null],
    ['fire', 'cfb', 'Firewall???', null],
    // ['prob', '', '', null],
    ['srcv', 'str', 'Source Version', null],
    ['syNm', 'str', 'Device name', null],
    // ['syDN', '', '', null],
    // ['syPI', '', '', null],
    ['syPW', 'str', 'Router administration password', null],
    ['syPR', 'str', 'syPR string???', null],
    ['syGP', 'str', 'Router guest password???', null],
    // ['syCt', '', '', null],
    // ['syLo', '', '', null],
    ['syDs', 'str', 'System description', null],
    ['syVs', 'str', 'System version', null],
    ['syVr', 'str', 'System version???', null],
    ['syIn', 'str', 'System information???', null],
    ['syFl', 'hex', '????', null],
    ['syAM', 'str', 'Model Identifier', null],
    ['syAP', 'dec', 'Product ID', null],
    ['sySN', 'str', 'Apple Serial Number', null],
    // ['ssSN', '', '', null],
    // ['sySK', '', '', null],
    ['ssSK', 'str', 'Apple SKU', null],
    // ['syRe', '', '', null],
    ['syLR', 'cfb', 'syLR Blob', null],
    ['syAR', 'cfb', 'syAR Blob', null],
    ['syUT', 'dec', 'System Uptime', null],
    // ['minV', '', '', null],
    ['minS', 'str', 'apple-minver', null],
    ['chip', 'str', 'SoC Description', null],
    // ['card', '', '', null],
    // ['memF', '', '', null],
    // ['pool', '', '', null],
    // ['tmpC', '', '', null],
    // ['RPMs', '', '', null],
    ['sySI', 'cfb', 'System Info Blob?', null],
    // ['fDCY', '', '', null],
    ['TMEn', 'hex', 'TMEn???', null],
    ['CLTM', 'cfb', 'CLTM???', null],
    // ['sPLL', '', '', null],
    // ['syTL', '', '', null],
    // ['syST', '', '', null],
    ['sySt', 'cfb', 'System Status', null],
    // ['syIg', '', '', null],
    ['syBL', 'str', 'Bootloader vesrsion string', null],
    ['time', 'dec', 'System time', null],
    ['timz', 'cfb', 'Timezone Config Blob', null],
    ['usrd', 'cfb', 'usrd???', null],
    // ['uuid', '', '', null],
    // ['drTY', '', '', null],
    // ['sttE', '', '', null],
    // ['sttF', '', '', null],
    // ['stat', '', '', null],
    // ['sRnd', '', '', null],
    // ['Accl', '', '', null],
    ['dSpn', 'cfb', 'Disk spin status?', null],
    ['syMS', 'str', 'MLB Serial Number', null],
    // ['IGMP', '', '', null],
    ['diag', 'bin', 'diag???', null],
    // ['paFR', '', '', null],
    ['raNm', 'str', 'Radio Name', null],
    // ['raCl', '', '', null],
    // ['raSk', '', '', null],
    // ['raWM', '', '', null],
    // ['raEA', '', '', null],
    // ['raWE', '', '', null],
    // ['raCr', '', '', null],
    // ['raKT', '', '', null],
    // ['raNN', '', '', null],
    // ['raGK', '', '', null],
    // ['raHW', '', '', null],
    // ['raCM', '', '', null],
    // ['raRo', '', '', null],
    // ['raCA', '', '', null],
    // ['raCh', '', '', null],
    // ['rCh2', '', '', null],
    // ['raWC', '', '', null],
    // ['raDe', '', '', null],
    // ['raMu', '', '', null],
    // ['raLC', '', '', null],
    // ['raLF', '', '', null],
    // ['ra1C', '', '', null],
    // ['raVs', '', '', null],
    ['raMA', 'mac', 'Radio MAC Address', null],
    // ['raM2', '', '', null],
    // ['raMO', '', '', null],
    // ['raLO', '', '', null],
    // ['raDS', '', '', null],
    // ['raNA', '', '', null],
    // ['raWB', '', '', null],
    // ['raIS', '', '', null],
    // ['raMd', '', '', null],
    // ['raPo', '', '', null],
    // ['raPx', '', '', null],
    // ['raTr', '', '', null],
    // ['raDt', '', '', null],
    // ['raFC', '', '', null],
    // ['raEC', '', '', null],
    // ['raMX', '', '', null],
    // ['raIE', '', '', null],
    // ['raII', '', '', null],
    // ['raB0', '', '', null],
    // ['raB1', '', '', null],
    // ['raB2', '', '', null],
    // ['raSt', '', '', null],
    // ['APSR', '', '', null],
    // ['raTX', '', '', null],
    // ['raRX', '', '', null],
    // ['raAC', '', '', null],
    ['raSL', 'cfb', 'Radios list?', null],
    // ['raMI', '', '', null],
    // ['raST', '', '', null],
    // ['raDy', '', '', null],
    // ['raEV', '', '', null],
    // ['rTSN', '', '', null],
    ['raSR', 'cfb', 'Radio scan results?', null],
    // ['eaRA', '', '', null],
    ['WiFi', 'cfb', 'Wifi configuration?', null],
    ['rCAL', 'cfb', 'Radio calibration data?', null],
    // ['moPN', '', '', null],
    // ['moAP', '', '', null],
    // ['moUN', '', '', null],
    // ['moPW', '', '', null],
    // ['moIS', '', '', null],
    // ['moLS', '', '', null],
    // ['moLI', '', '', null],
    // ['moID', '', '', null],
    // ['moDT', '', '', null],
    // ['moPD', '', '', null],
    // ['moAD', '', '', null],
    // ['moCC', '', '', null],
    // ['moCR', '', '', null],
    // ['moCI', '', '', null],
    // ['^moM', '', '', null],
    // ['moVs', '', '', null],
    // ['moMP', '', '', null],
    // ['moMF', '', '', null],
    // ['moFV', '', '', null],
    // ['pdFl', '', '', null],
    // ['pdUN', '', '', null],
    // ['pdPW', '', '', null],
    // ['pdAR', '', '', null],
    // ['pdID', '', '', null],
    // ['pdMC', '', '', null],
    // ['peSN', '', '', null],
    // ['peUN', '', '', null],
    // ['pePW', '', '', null],
    // ['peSC', '', '', null],
    // ['peAC', '', '', null],
    // ['peID', '', '', null],
    // ['peAO', '', '', null],
    ['waCV', 'bin', 'WAN Config Mode?', null],
    ['waIn', 'bin', 'WAN Interface Mode?', null],
    // ['waD1', '', '', null],
    // ['waD2', '', '', null],
    // ['waD3', '', '', null],
    // ['waC1', '', '', null],
    // ['waC2', '', '', null],
    // ['waC3', '', '', null],
    ['waIP', 'bin', 'WAN IP', null],
    // ['waSM', '', '', null],
    ['waRA', 'bin', 'WAN Upstream Gateway IP', null],
    // ['waDC', '', '', null],
    // ['waDS', '', '', null],
    ['waMA', 'mac', 'WAN MAC Address', null],
    // ['waMO', '', '', null],
    // ['waDN', '', '', null],
    // ['waCD', '', '', null],
    // ['waIS', '', '', null],
    // ['waNM', '', '', null],
    // ['waSD', '', '', null],
    // ['waFF', '', '', null],
    // ['waRO', '', '', null],
    // ['waW1', '', '', null],
    // ['waW2', '', '', null],
    // ['waW3', '', '', null],
    // ['waLL', '', '', null],
    // ['waUB', '', '', null],
    ['waDI', 'cfb', 'WAN DHCP Info?', null],
    // ['laCV', '', '', null],
    // ['laIP', '', '', null],
    // ['laSM', '', '', null],
    // ['laRA', '', '', null],
    // ['laDC', '', '', null],
    // ['laDS', '', '', null],
    // ['laNA', '', '', null],
    ['laMA', 'mac', 'LAN MAC Address', null],
    // ['laIS', '', '', null],
    // ['laSD', '', '', null],
    // ['laIA', '', '', null],
    // ['gn6?', '', '', null],
    // ['gn6A', '', '', null],
    // ['gn6P', '', '', null],
    // ['dhFl', '', '', null],
    // ['dhBg', '', '', null],
    // ['dhEn', '', '', null],
    // ['dhSN', '', '', null],
    // ['dhRo', '', '', null],
    // ['dhLe', '', '', null],
    // ['dhMg', '', '', null],
    // ['dh95', '', '', null],
    ['DRes', 'cfb', 'DHCP Reservations', null],
    // ['dhWA', '', '', null],
    // ['dhDS', '', '', null],
    // ['dhDB', '', '', null],
    // ['dhDE', '', '', null],
    // ['dhDL', '', '', null],
    ['dhSL', 'cfb', 'DHCP Server leases?', null],
    // ['gnFl', '', '', null],
    // ['gnBg', '', '', null],
    // ['gnEn', '', '', null],
    // ['gnSN', '', '', null],
    // ['gnRo', '', '', null],
    // ['gnLe', '', '', null],
    // ['gnMg', '', '', null],
    // ['gn95', '', '', null],
    // ['gnDi', '', '', null],
    // ['naFl', '', '', null],
    // ['naBg', '', '', null],
    // ['naEn', '', '', null],
    // ['naSN', '', '', null],
    // ['naRo', '', '', null],
    // ['naAF', '', '', null],
    // ['nDMZ', '', '', null],
    // ['pmPI', '', '', null],
    // ['pmPS', '', '', null],
    // ['pmPR', '', '', null],
    // ['pmTa', '', '', null],
    // ['acEn', '', '', null],
    // ['acTa', '', '', null],
    ['tACL', 'cfb', 'Timed Access Control', null],
    // ['wdFl', '', '', null],
    // ['wdLs', '', '', null],
    // ['dWDS', '', '', null],
    // ['cWDS', '', '', null],
    // ['dwFl', '', '', null],
    // ['raFl', '', '', null],
    // ['raI1', '', '', null],
    // ['raTm', '', '', null],
    // ['raAu', '', '', null],
    // ['raAc', '', '', null],
    // ['raSe', '', '', null],
    // ['raRe', '', '', null],
    // ['raF2', '', '', null],
    // ['raI2', '', '', null],
    // ['raT2', '', '', null],
    // ['raU2', '', '', null],
    // ['raC2', '', '', null],
    // ['raS2', '', '', null],
    // ['raR2', '', '', null],
    // ['raCi', '', '', null],
    ['ntSV', 'str', 'NTP Server Hostname', null],
    // ['ntpC', '', '', null],
    // ['smtp', '', '', null],
    // ['slog', '', '', null],
    // ['slgC', '', '', null],
    // ['slCl', '', '', null],
    ['slvl', 'dec', 'System log severity level?', null],
    // ['slfl', '', '', null],
    ['logm', 'log', 'System log data', null],
    // ['snAF', '', '', null],
    // ['snLW', '', '', null],
    // ['snLL', '', '', null],
    // ['snRW', '', '', null],
    // ['snWW', '', '', null],
    // ['snRL', '', '', null],
    // ['snWL', '', '', null],
    // ['snCS', '', '', null],
    // ['srtA', '', '', null],
    // ['srtF', '', '', null],
    // ['upsF', '', '', null],
    // ['usbF', '', '', null],
    ['USBi', 'cfb', 'USB Info', null],
    // ['USBL', '', '', null],
    // ['USBR', '', '', null],
    // ['USBO', '', '', null],
    // ['USBs', '', '', null],
    // ['USBo', '', '', null],
    // ['USBh', '', '', null],
    // ['USBb', '', '', null],
    // ['USBn', '', '', null],
    ['prni', 'cfb', 'Printer Info?', null],
    // ['prnM', '', '', null],
    // ['prnI', '', '', null],
    // ['prnR', '', '', null],
    // ['RUdv', '', '', null],
    // ['RUfl', '', '', null],
    ['MaSt', 'cfb', 'USB Mass Storage Info', null],
    // ['SMBw', '', '', null],
    // ['SMBs', '', '', null],
    // ['fssp', '', '', null],
    // ['diSD', '', '', null],
    // ['diCS', '', '', null],
    // ['deSt', '', '', null],
    // ['daSt', '', '', null],
    // ['dmSt', '', '', null],
    // ['adNm', '', '', null],
    // ['adBD', '', '', null],
    // ['adAD', '', '', null],
    // ['adHU', '', '', null],
    // ['IDNm', '', '', null],
    ['seFl', 'bin', '????', null], // ????
    // ['nvVs', '', '', null],
    // ['dbRC', '', '', null],
    ['dbug', 'hex', 'Debug flags', function ($value) {
        return 0 <= $value && $value <= 0xffffffff;
    }],
    // ['dlvl', '', '', null],
    // ['dcmd', '', '', null],
    // ['dsps', '', '', null],
    // ['logC', '', '', null],
    // ['cver', '', '', null],
    ['ctim', 'hex', 'ctim???', null],
    // ['svMd', '', '', null],
    // ['serM', '', '', null],
    // ['serT', '', '', null],
    // ['emNo', '', '', null],
    // ['effF', '', '', null],
    // ['LLnk', '', '', null],
    // ['WLnk', '', '', null],
    // ['PHYS', '', '', null],
    // ['PHYN', '', '', null],
    // ['Rnfo', '', '', null],
    // ['evtL', '', '', null],
    // ['isAC', '', '', null],
    // ['Adet', '', '', null],
    ['Prof', 'cfb', 'Restore Profile Blob', null],
    // ['maAl', '', '', null],
    // ['maPr', '', '', null],
    // ['leAc', '', '', null],
    // ['APID', '', '', null],
    // ['AAU ', '', '', null],
    ['lcVs', 'str', 'lcVs Version String?', null],
    // ['lcVr', '', '', null],
    // ['lcmV', '', '', null],
    // ['lcMV', '', '', null],
    // ['iMTU', '', '', null],
    ['wsci', 'cfb', 'wsci Blob', null],
    // ['FlSu', '', '', null],
    ['OTPR', 'hex', 'machdep.otpval', null],
    ['acRB', 'dec', 'Reboot device flag', function ($value) {
        return $value === 0;
    }],
    ['acRI', 'dec', 'Reload services??', function ($value) {
        return $value === 0;
    }],
    // ['acPC', '', '', null],
    // ['acDD', '', '', null],
    // ['acPD', '', '', null],
    // ['acPG', '', '', null],
    // ['acDS', '', '', null],
    // ['acFN', '', '', null],
    // ['acRP', '', '', null],
    ['acRN', 'dec', 'Resets something... (?)', function ($value) {
        return $value === 0;
    }],
    ['acRF', 'dec', 'Reset to factory defaults', function ($value) {
        return $value === 0;
    }],
    // ['MdmH', '', '', null],
    // ['dirf', '', '', null],
    // ['Afrc', '', '', null],
    // ['lebl', '', '', null],
    // ['lebs', '', '', null],
    ['LEDc', 'dec', 'LED color/pattern', function ($value) {
        return 0 <= $value && $value <= 3;
    }],
    // ['acEf', '', '', null],
    // ['invr', '', '', null],
    // ['FLSH', '', '', null],
    // ['acPL', '', '', null],
    // ['rReg', '', '', null],
    // ['dReg', '', '', null],
    ['GPIs', 'bin', 'GPIOs values', function ($value) {
        return strlen($value) === 8;
    }],
    // ['play', '', '', null],
    // ['paus', '', '', null],
    // ['ffwd', '', '', null],
    // ['rwnd', '', '', null],
    // ['itun', '', '', null],
    // ['plls', '', '', null],
    // ['User', '', '', null],
    // ['Pass', '', '', null],
    // ['itIP', '', '', null],
    // ['itpt', '', '', null],
    // ['daap', '', '', null],
    // ['song', '', '', null],
    // ['arti', '', '', null],
    // ['albm', '', '', null],
    // ['volm', '', '', null],
    // ['rvol', '', '', null],
    // ['Tcnt', '', '', null],
    // ['Bcnt', '', '', null],
    // ['shfl', '', '', null],
    // ['rept', '', '', null],
    // ['auPr', '', '', null],
    // ['auJD', '', '', null],
    // ['auNN', '', '', null],
    // ['auNP', '', '', null],
    // ['aFrq', '', '', null],
    // ['aChn', '', '', null],
    // ['aLvl', '', '', null],
    // ['aPat', '', '', null],
    // ['aSta', '', '', null],
    // ['aStp', '', '', null],
    // ['auCC', '', '', null],
    // ['acmp', '', '', null],
    // ['aenc', '', '', null],
    // ['anBf', '', '', null],
    // ['aWan', '', '', null],
    // ['auRR', '', '', null],
    // ['auMt', '', '', null],
    // ['aDCP', '', '', null],
    // ['DCPc', '', '', null],
    // ['DACP', '', '', null],
    // ['DCPi', '', '', null],
    // ['auSl', '', '', null],
    // ['auFl', '', '', null],
    ['fe01', 'hex', '????', null],
    ['feat', 'str', 'Supported features?', null],
    ['prop', 'str', 'Valid acp properties', null],
    ['hw01', 'hex', '????', null],
    // ['fltr', '', '', null],
    // ['wdel', '', '', null],
    // ['plEB', '', '', null],
    // ['rWSC', '', '', null],
    // ['uDFS', '', '', null],
    // ['dWPA', '', '', null],
    // ['dpFF', '', '', null],
    // ['duLF', '', '', null],
    // ['ieHT', '', '', null],
    // ['dwlX', '', '', null],
    // ['dd11', '', '', null],
    // ['dRdr', '', '', null],
    // ['dotD', '', '', null],
    // ['dotH', '', '', null],
    // ['dPwr', '', '', null],
    // ['wlBR', '', '', null],
    // ['iTIM', '', '', null],
    // ['idAG', '', '', null],
    // ['mvFL', '', '', null],
    // ['mvFM', '', '', null],
    // ['dPPP', '', '', null],
    // ['!mta', '', '', null],
    // ['minR', '', '', null],
    // ['SpTr', '', '', null],
    // ['dRBT', '', '', null],
    // ['dRIR', '', '', null],
    ['pECC', 'cfb', 'PCIe ECC Blob?', null],
    // ['fxEB', '', '', null],
    // ['fxID', '', '', null],
    // ['fuup', '', '', null],
    // ['fust', '', '', null],
    // ['fuca', '', '', null],
    ['fugp', 'str', 'Firmware upgrade progress', null],
    ['cks0', 'hex', 'Bootloader Flash Checksum', null],
    ['cks1', 'hex', 'Primary Flash Checksum', null],
    ['cks2', 'hex', 'Secondary Flash Checksum', null],
    // ['ddBg', '', '', null],
    // ['ddEn', '', '', null],
    // ['ddIn', '', '', null],
    // ['ddSm', '', '', null],
    // ['ddEC', '', '', null],
    // ['ddFE', '', '', null],
    // ['ddSR', '', '', null],
    // ['6cfg', '', '', null],
    // ['6aut', '', '', null],
    // ['6Qpd', '', '', null],
    // ['6Wad', '', '', null],
    // ['6Wfx', '', '', null],
    // ['6Wgw', '', '', null],
    // ['6Wte', '', '', null],
    // ['6Lfw', '', '', null],
    // ['6Lad', '', '', null],
    // ['6Lfx', '', '', null],
    // ['6sfw', '', '', null],
    // ['6pmp', '', '', null],
    // ['6trd', '', '', null],
    // ['6sec', '', '', null],
    // ['6fwl', '', '', null],
    // ['6NS1', '', '', null],
    // ['6NS2', '', '', null],
    // ['6NS3', '', '', null],
    // ['6ahr', '', '', null],
    // ['6dhs', '', '', null],
    // ['6dso', '', '', null],
    // ['6PDa', '', '', null],
    // ['6PDl', '', '', null],
    // ['6vlt', '', '', null],
    // ['6plt', '', '', null],
    // ['6CWa', '', '', null],
    // ['6CWp', '', '', null],
    // ['6CWg', '', '', null],
    // ['6CLa', '', '', null],
    // ['6NSa', '', '', null],
    // ['6NSb', '', '', null],
    // ['6NSc', '', '', null],
    // ['6CPa', '', '', null],
    // ['6CPl', '', '', null],
    // ['6!at', '', '', null],
    ['rteI', 'cfb', 'rteI Blob', null],
    // ['PCLI', '', '', null],
    // ['dxEM', '', '', null],
    // ['dxID', '', '', null],
    // ['dxAI', '', '', null],
    // ['dxIP', '', '', null],
    // ['dxOA', '', '', null],
    // ['dxIA', '', '', null],
    // ['dxC1', '', '', null],
    // ['dxP1', '', '', null],
    // ['dxC2', '', '', null],
    // ['dxP2', '', '', null],
    // ['bjFl', '', '', null],
    // ['bjSd', '', '', null],
    // ['bjSM', '', '', null],
    // ['wbEn', '', '', null],
    // ['wbHN', '', '', null],
    // ['wbHU', '', '', null],
    // ['wbHP', '', '', null],
    // ['wbRD', '', '', null],
    // ['wbRU', '', '', null],
    // ['wbRP', '', '', null],
    // ['wbAC', '', '', null],
    // ['dMac', '', '', null],
    // ['iCld', '', '', null],
    // ['iCLH', '', '', null],
    // ['iCLB', '', '', null],
    // ['SUEn', '', '', null],
    // ['SUAI', '', '', null],
    // ['SUFq', '', '', null],
    // ['SUSv', '', '', null],
    // ['suPR', '', '', null],
    // ['msEn', '', '', null],
    // ['trCo', '', '', null],
    // ['EZCF', '', '', null],
    // ['ezcf', '', '', null],
    // ['gVID', '', '', null],
    // ['wcfg', '', '', null],
    // ['awce', '', '', null],
    // ['wcgu', '', '', null],
    // ['wcgs', '', '', null],
    // ['awcc', '', '', null]
];
